name:
  simulink_pipeline

on:
  push:
    branches: [ master ]

permissions:
  checks:
    write

  contents:
    read


# env:
#   PATH_TO_MATLAB:
#     PATH_TO_MATLAB


jobs:
  Restore_Cache:
    runs-on:
      ubuntu-latest

    steps:
      - name:
          Checkout Repository

        uses:
          actions/checkout@v4

      - name:
          Restore Cache

        uses:
          actions/cache@v4

        with:
          key:
            padv_artifacts-${{ runner.os }}-${{ github.ref_name }}

          restore-keys: |
            padv_artifacts-${{ runner.os }}-
            padv_artifacts-

          path: |
            derived/artifacts.dmr
            AutoCodeGen
            PA_Results/CalculateFeedforwardVoltages/model_standards_results
            PA_Results/CalculateMaximumFluxLimit/model_standards_results
            PA_Results/CalculateOptimalFlux/model_standards_results
            PA_Results/CalculateTorqueLimits/model_standards_results
            PA_Results/FluxWeakeningControl/model_standards_results
            PA_Results/RsCalculation/model_standards_results
            PA_Results/TractionEmotorRequirements/report
            PA_Results/test_results



      - name:
          Upload Artifacts

        if:
          ${{ !cancelled() }}

        uses:
          actions/upload-artifact@v4

        with:
          name: restore_cache_artifacts

          path: |
            derived/artifacts.dmr
            AutoCodeGen
            PA_Results/CalculateFeedforwardVoltages/model_standards_results
            PA_Results/CalculateMaximumFluxLimit/model_standards_results
            PA_Results/CalculateOptimalFlux/model_standards_results
            PA_Results/CalculateTorqueLimits/model_standards_results
            PA_Results/FluxWeakeningControl/model_standards_results
            PA_Results/RsCalculation/model_standards_results
            PA_Results/TractionEmotorRequirements/report
            PA_Results/test_results

          retention-days:
            30



  Runprocess:
    if:
      ${{ !cancelled() }}

    needs:
      Restore_Cache

    runs-on:
      ubuntu-latest

    env:
      # Secure secret injection (job-level)
      MLM_LICENSE_TOKEN: ${{ secrets.MATLAB_BATCH_TOKEN }}

    steps:
      - name:
          Checkout Repository

        uses:
          actions/checkout@v4

      - name:
          Download Artifacts
        continue-on-error: true
        uses:
          actions/download-artifact@v4
        
        with:
          name:
            restore_cache_artifacts


      - name:
          Setup MATLAB

        uses: matlab-actions/setup-matlab@v2
        with:
          release: R2025b
          cache: true
          products: |
            Simulink
            Stateflow
            Simulink_Test
            Simulink_Coverage
            Simulink_Check
            Requirements_Toolbox
            CI/CD_Automation_for_Simulink_Check
            MATLAB_Coder
            Simulink_Coder
            Embedded_Coder
            System_Composer
            Simulink_Design_Verifier
            Powertrain_Blockset
            Simulink_Report_Generator
            Simulink_Control_Design

      - name: Run MATLAB CI process
        uses: matlab-actions/run-command@v2
        with:
          command: |
            openProject(pwd);
            runprocess( ...
              Process="CIPipeline", ...
              Force=false, ...
              ExitInBatchMode=true, ...
              RerunFailedTasks=false, ...
              RerunErroredTasks=false, ...
              GenerateJUnitForProcess=true);
              
      - name:
          Upload Artifacts

        if:
          ${{ !cancelled() }}

        uses:
          actions/upload-artifact@v4

        with:
          name:
            Runprocess_padv_artifacts

          path: |
            derived/artifacts.dmr
            AutoCodeGen
            PA_Results/CalculateFeedforwardVoltages/model_standards_results
            PA_Results/CalculateMaximumFluxLimit/model_standards_results
            PA_Results/CalculateOptimalFlux/model_standards_results
            PA_Results/CalculateTorqueLimits/model_standards_results
            PA_Results/FluxWeakeningControl/model_standards_results
            PA_Results/RsCalculation/model_standards_results
            PA_Results/TractionEmotorRequirements/report
            PA_Results/test_results

          retention-days:
            30



  Collect_Artifacts:
    if:
      ${{ !cancelled() }}

    needs:
      Runprocess

    runs-on: ubuntu-latest
      
    steps:
      - name:
          Download Artifacts
      
        uses:
          actions/download-artifact@v4
        continue-on-error: true
        with:
          name: restore_cache_artifacts 
 
      - name: Download runprocess artifact
        uses: actions/download-artifact@v4
        continue-on-error: true
        with:
          name: runprocess_artifacts


      - name: Save Cache
        uses: actions/cache@v4
        with:
          key: padv_artifacts-${{ runner.os }}-${{ github.ref_name }}-${{ github.sha }}
          restore-keys: |
            padv_artifacts-${{ runner.os }}-${{ github.ref_name }}
            padv_artifacts-${{ runner.os }}-
            adv_artifacts-
          path: |
            AutoCodeGen
            PA_Results/CalculateFeedforwardVoltages/model_standards_results
            PA_Results/CalculateMaximumFluxLimit/model_standards_results
            PA_Results/CalculateOptimalFlux/model_standards_results
            PA_Results/CalculateTorqueLimits/model_standards_results
            PA_Results/FluxWeakeningControl/model_standards_results
            PA_Results/RsCalculation/model_standards_results
            PA_Results/TractionEmotorRequirements/report
            PA_Results/test_results
            derived/artifacts.dmr

